// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: integrations.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IntegrationServiceClient is the client API for IntegrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntegrationServiceClient interface {
	FetchOrcidAchievements(ctx context.Context, in *OrcidRequest, opts ...grpc.CallOption) (*OrcidResponse, error)
	FetchOpenAlexAchievements(ctx context.Context, in *OpenAlexRequest, opts ...grpc.CallOption) (*OpenAlexResponse, error)
	SyncAllAchievements(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	CrawlAchievements(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error)
	CrawlDevActivity(ctx context.Context, in *DevActivityRequest, opts ...grpc.CallOption) (*DevActivityResponse, error)
}

type integrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationServiceClient(cc grpc.ClientConnInterface) IntegrationServiceClient {
	return &integrationServiceClient{cc}
}

func (c *integrationServiceClient) FetchOrcidAchievements(ctx context.Context, in *OrcidRequest, opts ...grpc.CallOption) (*OrcidResponse, error) {
	out := new(OrcidResponse)
	err := c.cc.Invoke(ctx, "/integrations.IntegrationService/FetchOrcidAchievements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) FetchOpenAlexAchievements(ctx context.Context, in *OpenAlexRequest, opts ...grpc.CallOption) (*OpenAlexResponse, error) {
	out := new(OpenAlexResponse)
	err := c.cc.Invoke(ctx, "/integrations.IntegrationService/FetchOpenAlexAchievements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) SyncAllAchievements(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/integrations.IntegrationService/SyncAllAchievements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) CrawlAchievements(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error) {
	out := new(CrawlResponse)
	err := c.cc.Invoke(ctx, "/integrations.IntegrationService/CrawlAchievements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationServiceClient) CrawlDevActivity(ctx context.Context, in *DevActivityRequest, opts ...grpc.CallOption) (*DevActivityResponse, error) {
	out := new(DevActivityResponse)
	err := c.cc.Invoke(ctx, "/integrations.IntegrationService/CrawlDevActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationServiceServer is the server API for IntegrationService service.
// All implementations must embed UnimplementedIntegrationServiceServer
// for forward compatibility
type IntegrationServiceServer interface {
	FetchOrcidAchievements(context.Context, *OrcidRequest) (*OrcidResponse, error)
	FetchOpenAlexAchievements(context.Context, *OpenAlexRequest) (*OpenAlexResponse, error)
	SyncAllAchievements(context.Context, *SyncRequest) (*SyncResponse, error)
	CrawlAchievements(context.Context, *CrawlRequest) (*CrawlResponse, error)
	CrawlDevActivity(context.Context, *DevActivityRequest) (*DevActivityResponse, error)
	mustEmbedUnimplementedIntegrationServiceServer()
}

// UnimplementedIntegrationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntegrationServiceServer struct {
}

func (UnimplementedIntegrationServiceServer) FetchOrcidAchievements(context.Context, *OrcidRequest) (*OrcidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchOrcidAchievements not implemented")
}
func (UnimplementedIntegrationServiceServer) FetchOpenAlexAchievements(context.Context, *OpenAlexRequest) (*OpenAlexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchOpenAlexAchievements not implemented")
}
func (UnimplementedIntegrationServiceServer) SyncAllAchievements(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncAllAchievements not implemented")
}
func (UnimplementedIntegrationServiceServer) CrawlAchievements(context.Context, *CrawlRequest) (*CrawlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlAchievements not implemented")
}
func (UnimplementedIntegrationServiceServer) CrawlDevActivity(context.Context, *DevActivityRequest) (*DevActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlDevActivity not implemented")
}
func (UnimplementedIntegrationServiceServer) mustEmbedUnimplementedIntegrationServiceServer() {}

// UnsafeIntegrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrationServiceServer will
// result in compilation errors.
type UnsafeIntegrationServiceServer interface {
	mustEmbedUnimplementedIntegrationServiceServer()
}

func RegisterIntegrationServiceServer(s grpc.ServiceRegistrar, srv IntegrationServiceServer) {
	s.RegisterService(&IntegrationService_ServiceDesc, srv)
}

func _IntegrationService_FetchOrcidAchievements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrcidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).FetchOrcidAchievements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integrations.IntegrationService/FetchOrcidAchievements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).FetchOrcidAchievements(ctx, req.(*OrcidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_FetchOpenAlexAchievements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenAlexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).FetchOpenAlexAchievements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integrations.IntegrationService/FetchOpenAlexAchievements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).FetchOpenAlexAchievements(ctx, req.(*OpenAlexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_SyncAllAchievements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).SyncAllAchievements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integrations.IntegrationService/SyncAllAchievements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).SyncAllAchievements(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_CrawlAchievements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).CrawlAchievements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integrations.IntegrationService/CrawlAchievements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).CrawlAchievements(ctx, req.(*CrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationService_CrawlDevActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServiceServer).CrawlDevActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integrations.IntegrationService/CrawlDevActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServiceServer).CrawlDevActivity(ctx, req.(*DevActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntegrationService_ServiceDesc is the grpc.ServiceDesc for IntegrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntegrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integrations.IntegrationService",
	HandlerType: (*IntegrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchOrcidAchievements",
			Handler:    _IntegrationService_FetchOrcidAchievements_Handler,
		},
		{
			MethodName: "FetchOpenAlexAchievements",
			Handler:    _IntegrationService_FetchOpenAlexAchievements_Handler,
		},
		{
			MethodName: "SyncAllAchievements",
			Handler:    _IntegrationService_SyncAllAchievements_Handler,
		},
		{
			MethodName: "CrawlAchievements",
			Handler:    _IntegrationService_CrawlAchievements_Handler,
		},
		{
			MethodName: "CrawlDevActivity",
			Handler:    _IntegrationService_CrawlDevActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integrations.proto",
}
