# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import integrations_pb2 as integrations__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in integrations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntegrationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchOrcidAchievements = channel.unary_unary(
                '/integrations.IntegrationService/FetchOrcidAchievements',
                request_serializer=integrations__pb2.OrcidRequest.SerializeToString,
                response_deserializer=integrations__pb2.OrcidResponse.FromString,
                _registered_method=True)
        self.FetchOpenAlexAchievements = channel.unary_unary(
                '/integrations.IntegrationService/FetchOpenAlexAchievements',
                request_serializer=integrations__pb2.OpenAlexRequest.SerializeToString,
                response_deserializer=integrations__pb2.OpenAlexResponse.FromString,
                _registered_method=True)
        self.SyncAllAchievements = channel.unary_unary(
                '/integrations.IntegrationService/SyncAllAchievements',
                request_serializer=integrations__pb2.SyncRequest.SerializeToString,
                response_deserializer=integrations__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.CrawlAchievements = channel.unary_unary(
                '/integrations.IntegrationService/CrawlAchievements',
                request_serializer=integrations__pb2.CrawlRequest.SerializeToString,
                response_deserializer=integrations__pb2.CrawlResponse.FromString,
                _registered_method=True)
        self.CrawlDevActivity = channel.unary_unary(
                '/integrations.IntegrationService/CrawlDevActivity',
                request_serializer=integrations__pb2.DevActivityRequest.SerializeToString,
                response_deserializer=integrations__pb2.DevActivityResponse.FromString,
                _registered_method=True)


class IntegrationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchOrcidAchievements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchOpenAlexAchievements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncAllAchievements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrawlAchievements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrawlDevActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntegrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchOrcidAchievements': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchOrcidAchievements,
                    request_deserializer=integrations__pb2.OrcidRequest.FromString,
                    response_serializer=integrations__pb2.OrcidResponse.SerializeToString,
            ),
            'FetchOpenAlexAchievements': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchOpenAlexAchievements,
                    request_deserializer=integrations__pb2.OpenAlexRequest.FromString,
                    response_serializer=integrations__pb2.OpenAlexResponse.SerializeToString,
            ),
            'SyncAllAchievements': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncAllAchievements,
                    request_deserializer=integrations__pb2.SyncRequest.FromString,
                    response_serializer=integrations__pb2.SyncResponse.SerializeToString,
            ),
            'CrawlAchievements': grpc.unary_unary_rpc_method_handler(
                    servicer.CrawlAchievements,
                    request_deserializer=integrations__pb2.CrawlRequest.FromString,
                    response_serializer=integrations__pb2.CrawlResponse.SerializeToString,
            ),
            'CrawlDevActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.CrawlDevActivity,
                    request_deserializer=integrations__pb2.DevActivityRequest.FromString,
                    response_serializer=integrations__pb2.DevActivityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'integrations.IntegrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('integrations.IntegrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntegrationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchOrcidAchievements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/integrations.IntegrationService/FetchOrcidAchievements',
            integrations__pb2.OrcidRequest.SerializeToString,
            integrations__pb2.OrcidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchOpenAlexAchievements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/integrations.IntegrationService/FetchOpenAlexAchievements',
            integrations__pb2.OpenAlexRequest.SerializeToString,
            integrations__pb2.OpenAlexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncAllAchievements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/integrations.IntegrationService/SyncAllAchievements',
            integrations__pb2.SyncRequest.SerializeToString,
            integrations__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrawlAchievements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/integrations.IntegrationService/CrawlAchievements',
            integrations__pb2.CrawlRequest.SerializeToString,
            integrations__pb2.CrawlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrawlDevActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/integrations.IntegrationService/CrawlDevActivity',
            integrations__pb2.DevActivityRequest.SerializeToString,
            integrations__pb2.DevActivityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
