[pytest]
testpaths = tests
asyncio_mode = auto
addopts =
    --cov=.
    --cov-report=term-missing
    --cov-report=html:coverage/html
    --cov-report=xml:coverage/coverage.xml
    --cov-config=.coveragerc
