FROM ghcr.io/cirruslabs/flutter:stable

WORKDIR /app

RUN flutter config --enable-web

COPY pubspec.yaml pubspec.lock ./
RUN flutter pub get

COPY . .

ENV API_BASE_URL=

CMD ["sh", "-c", "flutter run -d web-server --web-port 80 --web-hostname 0.0.0.0 --dart-define=API_BASE_URL=$API_BASE_URL"]
