development:
  adapter: redis
  url: <%= ENV.fetch("CABLE_REDIS_URL", ENV.fetch("REDIS_URL")) %>
  channel_prefix: research_activity_monitoring_system_development_cable

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("CABLE_REDIS_URL") { ENV.fetch("REDIS_URL").sub(%r{/\d+\z}, "/1") } %>
  channel_prefix: research_activity_monitoring_system_production







