services:
  db:
    image: postgres:14
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres:password@db:5432/research_activity_monitoring_system_production
      ANALYTICS_SERVICE_HOST: analytics:50051
      INTEGRATION_SERVICE_HOST: integration:50052
    depends_on:
      - db
      - analytics
      - integration

  analytics:
    build:
      context: ./analytics_service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/research_activity_monitoring_system_production?sslmode=disable
      PORT: 50051
    depends_on:
      - db

  integration:
    build:
      context: ./integration_service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/research_activity_monitoring_system_production?sslmode=disable
      PORT: 50052
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
