source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# ruby '3.2.2'

gem 'rails', '~> 7.0.0'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Business logic & pattern gems
gem 'dry-monads'
gem 'dry-validation'
gem 'dry-initializer'
gem 'interactor'

gem 'grpc'
gem 'google-protobuf'
gem 'grpc-tools'

gem 'bcrypt', '~> 3.1'
gem 'jwt', '~> 2.7'

gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.0'
gem 'sidekiq-scheduler', '~> 5.0'
gem 'connection_pool', '~> 2.4'

group :development, :test do
  gem 'debug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'listen', '~> 3.3'
  gem 'ffi', '>= 1.17.4'
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'simplecov', require: false
  gem 'simplecov-json', require: false
  gem 'rswag-specs'
end

group :development do
  gem 'anyway_config'
end

