# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reports.proto

require 'google/protobuf'

descriptor_data = "\n\rreports.proto\x12\x07reports\"8\n\x06\x46ilter\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x10\n\x08operator\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\")\n\x04Sort\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x12\n\ndescending\x18\x02 \x01(\x08\"\x93\x01\n\rReportRequest\x12\x13\n\x0breport_type\x18\x01 \x01(\t\x12 \n\x07\x66ilters\x18\x02 \x03(\x0b\x32\x0f.reports.Filter\x12\x1c\n\x05sorts\x18\x03 \x03(\x0b\x32\r.reports.Sort\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\x0e\n\x06offset\x18\x05 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x06 \x01(\t\"\xba\x01\n\x0eReportResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x13\n\x0btotal_count\x18\x03 \x01(\x05\x12@\n\rcolumn_totals\x18\x04 \x03(\x0b\x32).reports.ReportResponse.ColumnTotalsEntry\x1a\x33\n\x11\x43olumnTotalsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32W\n\x10\x41nalyticsService\x12\x43\n\x0eGenerateReport\x12\x16.reports.ReportRequest\x1a\x17.reports.ReportResponse\"\x00\x42\x06Z\x04./pbb\x06proto3"

begin
  ::Google::Protobuf::DescriptorPool.generated_pool.add_serialized_file(descriptor_data)
rescue => e
  # Игнорируем ошибку при повторной регистрации
  Rails.logger.debug "Protobuf descriptors already registered: #{e.message}"
end

module GrpcReports
  # Используем прямой путь к пулу, чтобы избежать проблем с областью видимости локальных переменных
  Filter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reports.Filter").msgclass
  Sort = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reports.Sort").msgclass
  ReportRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reports.ReportRequest").msgclass
  ReportResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reports.ReportResponse").msgclass
end
