# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: reports.proto for package 'reports'

require 'grpc'
require 'grpc_reports/reports_pb'

module GrpcReports
  module AnalyticsService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'reports.AnalyticsService'

      rpc :GenerateReport, ::GrpcReports::ReportRequest, ::GrpcReports::ReportResponse
    end

    Stub = Service.rpc_stub_class
  end
end
