# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations.proto

require 'grpc'
require 'grpc_integrations/integrations_pb'

module GrpcIntegrations
  module IntegrationService
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'integrations.IntegrationService'

      rpc :FetchOrcidAchievements, ::GrpcIntegrations::OrcidRequest, ::GrpcIntegrations::OrcidResponse
      rpc :SyncAllAchievements, ::GrpcIntegrations::SyncRequest, ::GrpcIntegrations::SyncResponse
    end

    Stub = Service.rpc_stub_class
  end
end

