# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations.proto

require 'google/protobuf'


descriptor_data = "\n\x12integrations.proto\x12\x0cintegrations\"\x1f\n\x0bSyncRequest\x12\x10\n\x08provider\x18\x01 \x01(\t\"E\n\x0cSyncResponse\x12\x35\n\x07results\x18\x01 \x03(\x0b\x32$.integrations.ResearcherAchievements\"\x87\x01\n\x16ResearcherAchievements\x12\x15\n\rresearcher_id\x18\x01 \x01(\x03\x12\x10\n\x08orcid_id\x18\x02 \x01(\t\x12\x13\n\x0bopenalex_id\x18\x03 \x01(\t\x12/\n\x0c\x61\x63hievements\x18\x04 \x03(\x0b\x32\x19.integrations.Achievement\" \n\x0cOrcidRequest\x12\x10\n\x08orcid_id\x18\x01 \x01(\t\"&\n\x0fOpenAlexRequest\x12\x13\n\x0bopenalex_id\x18\x01 \x01(\t\"C\n\x10OpenAlexResponse\x12/\n\x0c\x61\x63hievements\x18\x01 \x03(\x0b\x32\x19.integrations.Achievement\"\x9c\x01\n\x0b\x41\x63hievement\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x13\n\x0b\x65xternal_id\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x14\n\x0c\x61uthor_count\x18\x07 \x01(\x05\x12\x15\n\rjournal_title\x18\x08 \x01(\t\"@\n\rOrcidResponse\x12/\n\x0c\x61\x63hievements\x18\x01 \x03(\x0b\x32\x19.integrations.Achievement2\x97\x02\n\x12IntegrationService\x12S\n\x16\x46\x65tchOrcidAchievements\x12\x1a.integrations.OrcidRequest\x1a\x1b.integrations.OrcidResponse\"\x00\x12\\\n\x19\x46\x65tchOpenAlexAchievements\x12\x1d.integrations.OpenAlexRequest\x1a\x1e.integrations.OpenAlexResponse\"\x00\x12N\n\x13SyncAllAchievements\x12\x19.integrations.SyncRequest\x1a\x1a.integrations.SyncResponse\"\x00\x42\x06Z\x04./pbb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module GrpcIntegrations
  SyncRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("integrations.SyncRequest").msgclass
  SyncResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("integrations.SyncResponse").msgclass
  ResearcherAchievements = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("integrations.ResearcherAchievements").msgclass
  OrcidRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("integrations.OrcidRequest").msgclass
  OpenAlexRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("integrations.OpenAlexRequest").msgclass
  OpenAlexResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("integrations.OpenAlexResponse").msgclass
  Achievement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("integrations.Achievement").msgclass
  OrcidResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("integrations.OrcidResponse").msgclass
end
