# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: integrations.proto for package 'integrations'

require 'grpc'
require_relative 'integrations_pb'

module Integrations
  module IntegrationService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'integrations.IntegrationService'

      rpc :FetchOrcidAchievements, ::Integrations::OrcidRequest, ::Integrations::OrcidResponse
      rpc :FetchOpenAlexAchievements, ::Integrations::OpenAlexRequest, ::Integrations::OpenAlexResponse
      rpc :SyncAllAchievements, ::Integrations::SyncRequest, ::Integrations::SyncResponse
      rpc :CrawlAchievements, ::Integrations::CrawlRequest, ::Integrations::CrawlResponse
      rpc :CrawlDevActivity, ::Integrations::DevActivityRequest, ::Integrations::DevActivityResponse
    end

    Stub = Service.rpc_stub_class
  end
end
